language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.11'
  - '0.10'
  - 'node'
  - 'iojs'
notifications:
  email:
    recipients:
      - travisci@benary.org
    on_success: change
    on_failure: always

